# 선형회귀모형 

In [1]:
# 필요한 패키지 불러오기
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split  
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_squared_error
import statsmodels.api as sm
import statsmodels.formula.api as smf # R-style fourmula 사용: 0.5.0 version부터 제공

In [2]:
# CSV 파일 자료 읽기
white = pd.read_csv("white.csv")   # dataframe
white.head()    # white.tail()

x1    x2    x3    x4     x5    x6     x7      x8    x9   x10   x11  y
0  7.0  0.27  0.36  20.7  0.045  45.0  170.0  1.0010  3.00  0.45   8.8  6
1  6.3  0.30  0.34   1.6  0.049  14.0  132.0  0.9940  3.30  0.49   9.5  6
2  8.1  0.28  0.40   6.9  0.050  30.0   97.0  0.9951  3.26  0.44  10.1  6
3  7.2  0.23  0.32   8.5  0.058  47.0  186.0  0.9956  3.19  0.40   9.9  6
4  7.2  0.23  0.32   8.5  0.058  47.0  186.0  0.9956  3.19  0.40   9.9  6

In [3]:
white.y[0:10]         # white["y"][0:10]

0    6
1    6
2    6
3    6
4    6
5    6
6    6
7    6
8    6
9    6
Name: y, dtype: int64

In [4]:
# numpy를 이용한 자료 읽기
white_np = np.loadtxt('white.csv', skiprows=1, delimiter=',', dtype=np.float32) # array 형태
print(white_np[0:5,0:4])

[[ 7.    0.27  0.36 20.7 ]
 [ 6.3   0.3   0.34  1.6 ]
 [ 8.1   0.28  0.4   6.9 ]
 [ 7.2   0.23  0.32  8.5 ]
 [ 7.2   0.23  0.32  8.5 ]]


In [5]:
# 주요 기술통계
print(white.y.mean(axis=0,skipna = True),white.y.min(axis=0), white.y.max(axis=0),white.y.var(axis=0))
print(np.mean(white.y,0),np.min(white.y,0),np.max(white.y,0),np.var(white.y,0))

5.87790935075541 3 9 0.7843556854710759
5.87790935075541 3 9 0.7841955475197752


In [6]:
# y의 값이 숫자가 아닌 것을 제거
print(sum(np.isnan(white["y"])))
white = white[-np.isnan(white["y"])]  

0


In [7]:
## 설명변수, 반응변수 분리
X = np.array(white.drop(["y"],1));  y = np.array(white["y"])
X

array([[ 7.  ,  0.27,  0.36, ...,  3.  ,  0.45,  8.8 ],
       [ 6.3 ,  0.3 ,  0.34, ...,  3.3 ,  0.49,  9.5 ],
       [ 8.1 ,  0.28,  0.4 , ...,  3.26,  0.44, 10.1 ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  2.99,  0.46,  9.4 ],
       [ 5.5 ,  0.29,  0.3 , ...,  3.34,  0.38, 12.8 ],
       [ 6.  ,  0.21,  0.38, ...,  3.26,  0.32, 11.8 ]])

In [8]:
# train data & test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)  # array 형태
print(X_train[0:3])

[[7.2000e+00 2.1000e-01 3.7000e-01 1.6000e+00 4.9000e-02 2.3000e+01
  9.4000e+01 9.9240e-01 3.1600e+00 4.8000e-01 1.0900e+01]
 [5.7000e+00 1.5000e-01 2.8000e-01 3.7000e+00 4.5000e-02 5.7000e+01
  1.5100e+02 9.9130e-01 3.2200e+00 2.7000e-01 1.1200e+01]
 [7.0000e+00 2.7000e-01 4.8000e-01 6.1000e+00 4.2000e-02 6.0000e+01
  1.8400e+02 9.9566e-01 3.2000e+00 5.0000e-01 9.4000e+00]]


In [9]:
model = sm.OLS(y_train, sm.add_constant(X_train)) # sm.OLS(y,x)와 비교
results = model.fit()   # sm.OLS(y_train, sm.add_constant(X_train)).fit() 
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                  0.291
Method:                 Least Squares   F-statistic:                     129.1
Date:                Tue, 27 Aug 2019   Prob (F-statistic):          3.70e-248
Time:                        08:09:06   Log-Likelihood:                -3878.0
No. Observations:                3428   AIC:                             7780.
Df Residuals:                    3416   BIC:                             7854.
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        147.5394     21.311      6.923      0.0

In [10]:
smf.ols("y~x4+x6+x7+x11", data=white).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.217
Model:                            OLS   Adj. R-squared:                  0.216
Method:                 Least Squares   F-statistic:                     339.1
Date:                Tue, 27 Aug 2019   Prob (F-statistic):          5.31e-258
Time:                        08:09:07   Log-Likelihood:                -5755.3
No. Observations:                4898   AIC:                         1.152e+04
Df Residuals:                    4893   BIC:                         1.155e+04
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.1214      0.138     15.341      0.000       1.850       2.392
x4             0.0196      0.003      7.650      0.000       0.015       0.025
x6             0.0082      0.001      9.713      0.000       0.007       0.010
x7            -0.0021      0.000     -5.716      0.000      -0.003      -0.001
x11            0.3456      0.011     31.949      0.000       0.324       0.367
==============================================================================
Omnibus:                      111.670   Durbin-Watson:                   1.647
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              252.156
Skew:                           0.026   Prob(JB):                     1.76e-55
Kurtosis:                       4.110   Cond. No.                     1.86e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.86e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [11]:
 # sklearn package
lrm = LinearRegression(n_jobs=-1)     # 입력값형식: array-like(dataframe), matrix
# 옵션: fit_intercept = True, normalize=False, n_jobs=-1 ⇨ all CPUs are used
lrm.fit(X,y)
print(lrm.coef_)


[ 6.55199613e-02 -1.86317709e+00  2.20902007e-02  8.14828026e-02
 -2.47276537e-01  3.73276519e-03 -2.85747419e-04 -1.50284181e+02
  6.86343742e-01  6.31476473e-01  1.93475697e-01]


In [12]:
lrm.fit(X_train, y_train)
print(lrm.intercept_ , lrm.coef_ )

147.5394357375611 [ 8.00846101e-02 -1.70374343e+00  5.69767648e-02  8.17351234e-02
 -1.64381383e-02  4.96141486e-03 -4.74149230e-04 -1.48223181e+02
  7.49786197e-01  7.33900620e-01  2.08766177e-01]


In [13]:
# 예측값
forecast = lrm.predict(X_test)
print(forecast)

[6.13867211 4.87485387 5.80282258 ... 5.75952191 6.1982174  5.35556207]


In [14]:
# MSE
mean_squared_error(y_test,forecast)

0.5679515772489931

In [15]:
## LASSO, Ridge 
lasso = Lasso(alpha=0.1); ridge = Ridge(alpha=0.1)  # alpha=0: OLS
lasso.fit(X_train, y_train)
print(lasso.intercept_ , lasso.coef_ )

3.135011905022889 [-0.         -0.          0.          0.00658765 -0.          0.00931903
 -0.0026721  -0.          0.          0.          0.26000292]


In [16]:
forecast = lasso.predict(X_test[0:10,])
print(forecast)

[5.98542298 5.39795764 5.75828732 5.94075017 6.3486235  6.35493312
 5.74667097 6.083002   5.67070478 5.79674228]


In [17]:
## training-validation procedure(반복 with train-test-split)
result = np.zeros((10,5))
a = [0.01, 0.02, 0.03, 0.04, 0.05]
for step in range(10):
    X0, X1, y0, y1 = train_test_split(X, y, test_size=0.3)
    for choice in range(len(a)):
        lasso = Lasso(alpha=a[choice], normalize=True)
         # sklearn.preprocessing.StandardScaler
        lasso.fit(X0, y0) 
        forecast = lasso.predict(X1)
        result[step,choice] = mean_squared_error(y1,forecast)
print(result)

[[0.78552166 0.78552166 0.78552166 0.78552166 0.78552166]
 [0.80186213 0.80186213 0.80186213 0.80186213 0.80186213]
 [0.81248145 0.81248145 0.81248145 0.81248145 0.81248145]
 [0.74349976 0.74349976 0.74349976 0.74349976 0.74349976]
 [0.75027438 0.75027438 0.75027438 0.75027438 0.75027438]
 [0.81594542 0.81594542 0.81594542 0.81594542 0.81594542]
 [0.81258628 0.81258628 0.81258628 0.81258628 0.81258628]
 [0.80037357 0.80037357 0.80037357 0.80037357 0.80037357]
 [0.75587781 0.75587781 0.75587781 0.75587781 0.75587781]
 [0.80144995 0.80144995 0.80144995 0.80144995 0.80144995]]


# Tensorflow를 이용한 Regression analysis

In [18]:
# package 불러오기
import tensorflow as tf
import numpy as np

tf.__version__

'1.14.0'

In [19]:
# 데이터 읽기 및 분리
xy = np.loadtxt('white.csv', skiprows=1, delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [20]:
# 기존 그래프와 충돌방지
tf.reset_default_graph()

In [21]:
## Build graph using tensorflow operations
X = tf.placeholder(tf.float32, shape=[None, 11])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([11, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [22]:
# Linear regression
yhat = tf.matmul(X, W)+b
cost = tf.reduce_mean(tf.square(yhat-Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)   # AdamOptimizer
train = optimizer.minimize(cost)   

In [23]:
## feed data and run graph & update variables in the graph
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, Yhat_val, _ = sess.run([cost, yhat, train], feed_dict={X: x_data, Y: y_data})
    if step % 500 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", Yhat_val)


0 Cost:  42038.516 
Prediction:
 [[-234.76195]
 [-162.94432]
 [-143.65971]
 ...
 [-155.78502]
 [-150.3809 ]
 [-138.19211]]
500 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
1000 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
1500 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]
2000 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 ...
 [nan]
 [nan]
 [nan]]


## 자료의 표준화

In [24]:
def minmaxscaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    return numerator / denominator           
    # noise term prevents the zero division:  (denominator + 1e-7)

In [25]:
ymax, ymin = np.max(y_data), np.min(y_data)
print("min(Y)=",ymin,"\tmax(Y)=",ymax)
xy_scale = minmaxscaler(xy)
x_data = xy_scale[:, 0:-1]
y_data = xy_scale[:, [-1]]
print("min(Y_s)=",np.min(y_data),"\tmax(Y_s)=",np.max(y_data))
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state=100)


min(Y)= 3.0 	max(Y)= 9.0
min(Y_s)= 0.0 	max(Y_s)= 1.0


In [26]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(5001):
    cost_val, Yhat_val, _ = sess.run([cost, yhat, train], feed_dict={X: X_train, Y: y_train})
    if step % 1000 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", Yhat_val)

0 Cost:  2.9465487 
Prediction:
 [[-1.02705  ]
 [-1.5177876]
 [-1.7397369]
 ...
 [-1.3423736]
 [-1.1197066]
 [-0.9458568]]
1000 Cost:  0.11462104 
Prediction:
 [[ 0.5639404 ]
 [ 0.04148901]
 [-0.09560657]
 ...
 [ 0.41319305]
 [ 0.4259554 ]
 [ 0.5983192 ]]
2000 Cost:  0.10594891 
Prediction:
 [[ 0.60472345]
 [ 0.09236348]
 [-0.03233176]
 ...
 [ 0.46460783]
 [ 0.47732723]
 [ 0.63539803]]
3000 Cost:  0.100400925 
Prediction:
 [[ 0.599861  ]
 [ 0.09866679]
 [-0.01707309]
 ...
 [ 0.46563655]
 [ 0.48347318]
 [ 0.6285032 ]]
4000 Cost:  0.095396675 
Prediction:
 [[ 0.5940834 ]
 [ 0.10391325]
 [-0.00413895]
 ...
 [ 0.46545482]
 [ 0.48757726]
 [ 0.6210936 ]]
5000 Cost:  0.09086338 
Prediction:
 [[0.5886856 ]
 [0.10936081]
 [0.00790536]
 ...
 [0.46549073]
 [0.4909888 ]
 [0.6143923 ]]


In [27]:
#표준화된 데이터의 weights, bias 추정 
print("Weight\n",sess.run(W), "\nbias:",sess.run(b))   

Weight
 [[-0.08774281]
 [ 0.55103487]
 [-0.76723397]
 [ 1.3000622 ]
 [ 0.776293  ]
 [-1.7641325 ]
 [-0.979566  ]
 [-0.7604278 ]
 [-1.0477983 ]
 [ 0.7439249 ]
 [ 0.5664805 ]] 
bias: [0.93513066]


In [28]:
# 예측 & MSE
yhat = sess.run(yhat, feed_dict={X: X_test})
resid = (ymax-ymin)*(y_test-yhat)
print(resid[0:10])
print(sess.run(tf.reduce_mean(tf.square(resid))))

[[-0.07211995]
 [ 0.45860177]
 [ 1.7565773 ]
 [-0.06336594]
 [-0.4881277 ]
 [ 1.0800716 ]
 [ 0.3068061 ]
 [-2.3012044 ]
 [-0.7123053 ]
 [ 2.100865  ]]
3.4031768


# Tensorflow를 이용한 기본적인 Neural Network 모형

In [29]:
tf.reset_default_graph()
# Neural Network 설정
def multilayer_perceptron1(x, weights, biases):
    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1'])
    layer_1 = tf.nn.relu(layer_1)
    out_layer = tf.matmul(layer_1, weights['out']) + biases['out']
    return out_layer

In [30]:
## Build graph using tensorflow operations
n_hidden_1 = 36
n_input = X_train.shape[1]
X = tf.placeholder(tf.float32, shape=[None, n_input])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = {
    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'out': tf.Variable(tf.random_normal([n_hidden_1, n_input]))
}

B = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'out': tf.Variable(tf.random_normal([1]))
}

In [31]:
# Linear regression
yhat = multilayer_perceptron1(X, W, B)   #
cost = tf.reduce_mean(tf.square(yhat-Y))
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)   

In [32]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(20001):
    cost_val, _ = sess.run([cost, train], feed_dict={X: X_train, Y: y_train})
    if step % 2000 == 0:
        print(step, "Cost:", cost_val, "\n")

0 Cost: 22.076042 

2000 Cost: 0.0155729465 

4000 Cost: 0.014663008 

6000 Cost: 0.015056234 

8000 Cost: 0.014225225 

10000 Cost: 0.0138367 

12000 Cost: 0.0137619795 

14000 Cost: 0.013913987 

16000 Cost: 0.013791496 

18000 Cost: 0.013703878 

20000 Cost: 0.013778016 



In [33]:
#표준화된 데이터의 weights, bias 추정 
print("Weight\n",sess.run(W), "\nbias:",sess.run(B))   

Weight
 {'h1': array([[ 4.19410586e-01, -1.29329908e+00, -1.43222654e+00,
         5.95965326e-01, -4.17102516e-01, -1.14486468e+00,
         8.41097534e-02,  8.58534753e-01,  4.66499329e-01,
         1.36269897e-01, -8.61387253e-01, -7.80033946e-01,
        -1.03109860e+00,  1.17636347e+00, -8.51799965e-01,
         1.01564395e+00,  4.39494997e-01,  2.58049160e-01,
         8.86769116e-01, -1.11942363e+00,  5.61374903e-01,
         7.32633770e-01,  8.92332733e-01,  2.68417001e-01,
        -8.13811898e-01, -7.72404909e-01,  2.60366142e-01,
        -1.17118299e+00, -4.58491564e-01, -9.21143115e-01,
         1.53175527e-02, -1.24713731e+00, -1.02711463e+00,
        -3.57367098e-01, -1.64141953e-01,  2.66056746e-01],
       [-3.44580114e-02,  1.17931354e+00,  2.33103919e+00,
         1.37720382e+00, -1.48696482e+00,  1.00773346e+00,
         1.06010807e+00, -1.41633525e-01,  1.95311296e+00,
         1.69636035e+00, -1.33969641e+00, -8.37248504e-01,
         8.35343264e-03,  1.12940311e+00

In [34]:
# 예측 & MSE
yhat = sess.run(yhat, feed_dict={X: X_test})
resid = (ymax-ymin)*(y_test-yhat)
print(resid[0:10])
print(sess.run(tf.reduce_mean(tf.square(resid))))

[[ 0.9748124   0.9749676   1.0407797   0.99456775  1.0411931   1.0732845
   1.0893363   1.0949024   1.0720772   1.0513047   0.9991411 ]
 [ 0.16777807  0.17226487  0.2401455   0.19505721  0.2419079   0.27553707
   0.289604    0.2948497   0.27555066  0.2555521   0.20022422]
 [ 0.3005991   0.29644704  0.36957836  0.32541704  0.37484694  0.4083817
   0.42720294  0.43027854  0.39591622  0.37518668  0.31191015]
 [-0.2414875  -0.22047186 -0.16719389 -0.21001697 -0.16171288 -0.13442874
  -0.11152339 -0.11352253 -0.1295929  -0.14520836 -0.20868802]
 [-0.7327781  -0.7357435  -0.6667607  -0.7080796  -0.66248345 -0.6308005
  -0.6128819  -0.61079836 -0.6409972  -0.66017246 -0.721575  ]
 [-0.77144766 -0.77675843 -0.7079036  -0.7497704  -0.70590377 -0.6717632
  -0.6526344  -0.6512947  -0.6811502  -0.7025964  -0.7612202 ]
 [-0.15161347 -0.13369632 -0.07916808 -0.11996913 -0.0710392  -0.04790998
  -0.02776551 -0.02780414 -0.04626489 -0.0603869  -0.12033391]
 [ 0.17530489  0.18348098  0.24464393  0.2012

In [35]:
# 학습결과(weights, biases) 저장 및 반환
saver = tf.train.Saver()
saver.save(sess, "E:/인권이라이프/강의실에서/외부강의/통계학회/기계학습과 딥러닝-실습/parameters.ckpt")      # 반환: saver.restore(sess, "parameters.ckpt") 

'E:/인권이라이프/강의실에서/외부강의/통계학회/기계학습과 딥러닝-실습/parameters.ckpt'

In [36]:
tf.reset_default_graph()
# Layer가 2개로 구성된 NN
def multilayer_perceptron2(X, W, B, Rate):
    layer_1 = tf.add(tf.matmul(X, W['h1']), B['b1'])
    layer_1 = tf.nn.relu(layer_1)
    layer_1 = tf.nn.dropout(layer_1, rate=Rate)   ## rate = 1 - keep_prob : keep_prob는 이후 버전에서 제외될 예정
    layer_2 = tf.add(tf.matmul(layer_1,W['h2']),B['b2'])
    layer_2 = tf.nn.relu(layer_2)
    layer_2 = tf.nn.dropout(layer_2, rate=Rate)
    out_layer = tf.matmul(layer_2, W['out']) + B['out']
    return out_layer

In [37]:
## Build graph using tensorflow operations
n_hidden_1 = 36
n_hidden_2 = 36
n_input = X_train.shape[1]
Rate = tf.placeholder("float")
X = tf.placeholder(tf.float32, shape=[None, n_input])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = {
    'h1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'h2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_input]))
}
B = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([1]))
}


In [39]:
yhat = multilayer_perceptron2(X, W, B, Rate)   #
cost = tf.reduce_mean(tf.square(yhat-Y))
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)   

In [40]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(20001):
    cost_val, _ = sess.run([cost, train], feed_dict={X: X_train, Y: y_train, Rate:0.2})
    if step % 2000 == 0:
        print(step, "Cost: ", cost_val)

0 Cost:  953.60516
2000 Cost:  0.025460858
4000 Cost:  0.022146514
6000 Cost:  0.022438217
8000 Cost:  0.022121524
10000 Cost:  0.022121547
12000 Cost:  0.022121524
14000 Cost:  0.022121524
16000 Cost:  0.022121526
18000 Cost:  0.022121528
20000 Cost:  0.022121532


In [41]:
# 예측 & MSE
yhat = sess.run(yhat, feed_dict={X: X_test, Rate: 0.0})
resid = (ymax-ymin)*(y_test-yhat)
print(sess.run(tf.reduce_mean(tf.square(resid))))

0.755976


# Logistic Regression

In [42]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
import statsmodels.api as sm

In [43]:
white = pd.read_csv("white.csv")   # dataframe
white = white[-np.isnan(white["y"])]

In [44]:
## Logistic Regression()
white["good"] = (white.y > 5).astype(float)
X = np.array(white.drop(["y","good"],1))
y_binary = np.array(white["good"])
X_train, X_test, y_train, y_test = train_test_split(X, y_binary, test_size=0.3, random_state=100)

In [45]:
# statmodels
logit_sm = sm.Logit(y_train, sm.add_constant(X_train)).fit()
print(logit_sm.summary())     
   # logit_sm.params, logit_sm.fittedvalues(=eta), 
   # logit_sm.model.cdf(eta)

Optimization terminated successfully.
         Current function value: 0.508625
         Iterations 8
                           Logit Regression Results                           
Dep. Variable:                      y   No. Observations:                 3428
Model:                          Logit   Df Residuals:                     3416
Method:                           MLE   Df Model:                           11
Date:                Tue, 27 Aug 2019   Pseudo R-squ.:                  0.2100
Time:                        08:16:03   Log-Likelihood:                -1743.6
converged:                       True   LL-Null:                       -2206.9
                                        LLR p-value:                1.101e-191
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        202.1746     77.031      2.625      0.009      51.196     353.153
x1             0.0022      0.

In [46]:
muhat = logit_sm.predict(sm.add_constant(X_test))
(muhat > 0.5).astype(int)

array([1, 0, 1, ..., 1, 1, 0])

In [47]:
import statsmodels.formula.api as smf
model = "good ~ x4+x6+x7+x11"
logit_smf = smf.logit(formula=str(model),data=white).fit()
logit_smf.summary()

Optimization terminated successfully.
         Current function value: 0.540885
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   good   No. Observations:                 4898
Model:                          Logit   Df Residuals:                     4893
Method:                           MLE   Df Model:                            4
Date:                Tue, 27 Aug 2019   Pseudo R-squ.:                  0.1516
Time:                        08:16:07   Log-Likelihood:                -2649.3
converged:                       True   LL-Null:                       -3122.7
                                        LLR p-value:                1.149e-203
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -9.3557      0.480    -19.491      0.000     -10.296      -8.415
x4             0.0549      0.008      7.112      0.000       0.040       0.070
x6             0.0204      0.003      7.875      0.000       0.015       0.025
x7            -0.0059      0.001     -5.604      0.000      -0.008      -0.004
x11            0.9520      0.041     23.311      0.000       0.872       1.032
==============================================================================
"""

In [48]:
#sklearn : “statsmodels” 결과와 다름
from sklearn.linear_model import LogisticRegression
logitR = LogisticRegression()    
logitR.fit(X_train, y_train, sample_weight=None)  
print(logitR.coef_, logitR.intercept_)       # Ridge

[[-2.54268734e-01 -4.99157207e+00  7.03080675e-02  5.69184252e-02
  -5.18202072e-01  1.27063973e-02 -3.60579178e-03 -2.70489299e+00
  -5.22530573e-01  1.73828318e+00  9.39603772e-01]] [-2.70554792]


C:\Users\no1papa\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [49]:
logitL = LogisticRegression(penalty="l1")  # LASSO , C = 1/alpha    
logitL.fit(X_train, y_train, sample_weight=None)   
muL = logitL.predict_proba(X_test)
print(muL)

[[0.11567848 0.88432152]
 [0.84644301 0.15355699]
 [0.3825212  0.6174788 ]
 ...
 [0.36193797 0.63806203]
 [0.14776534 0.85223466]
 [0.67675905 0.32324095]]


C:\Users\no1papa\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [50]:
yhat = logitL.predict(X_test) 
print(yhat)

[1. 0. 1. ... 1. 1. 0.]


In [51]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, yhat))
print(pd.crosstab(index=y_test,columns=yhat))

[[241 219]
 [152 858]]
col_0  0.0  1.0
row_0          
0.0    241  219
1.0    152  858


In [52]:
print(1-metrics.accuracy_score(y_test,yhat))  # 오분류율   

0.2523809523809524


# Tensorflow를 이용한 Logistic Regression

In [53]:
import tensorflow as tf

tf.reset_default_graph()

xy = np.loadtxt('white.csv',skiprows=1, delimiter=',', dtype=np.float32)
y_binary = 1*(xy[:, [-1]] > 5)
print(y_binary[0:5])

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(); scaler.fit(xy); xy_scale = scaler.transform(xy)

x_data = xy_scale[:, 0:-1]
X_train, X_test, y_train, y_test = train_test_split(x_data, y_binary, test_size=0.3, random_state=1000)

[[1]
 [1]
 [1]
 [1]
 [1]]


In [54]:
# Logistic regression
X = tf.placeholder(tf.float32, shape=[None, 11])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([11, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [55]:
# logit link
mu = tf.sigmoid(tf.matmul(X, W) + b)    
# - log-likelihood function
cost = -tf.reduce_mean(Y*tf.log(mu)+(1-Y)*tf.log(1-mu)) 
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)  
train = optimizer.minimize(cost)    

In [56]:
predicted = tf.cast(mu > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [57]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        cost_val, _ = sess.run([cost, train],feed_dict={X: X_train, Y: y_train})
        if step % 200 == 0:
            print(step, cost_val)
    h, c, a = sess.run([mu, predicted, accuracy], feed_dict={X: X_test, Y: y_test})
print("\nMu: ", h, "\nPredict(Y): ", c, "\nAccuracy: ", a)

0 0.6390258
200 0.5486288
400 0.5262918
600 0.5167864
800 0.5123126
1000 0.510117
1200 0.5090335
1400 0.508509
1600 0.5082584
1800 0.508133
2000 0.50805855

Mu:  [[0.7713352 ]
 [0.9318801 ]
 [0.9562696 ]
 ...
 [0.8000567 ]
 [0.74424666]
 [0.34591797]] 
Predict(Y):  [[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [0.]] 
Accuracy:  0.75714284


# 다범주 로지스틱 모형

In [58]:
import numpy as np
from sklearn import datasets   
# iris data
iris = datasets.load_iris()
X = iris.data[:, :4]; Y = iris.target

In [59]:
import statsmodels.api as sm
X = sm.add_constant(X, prepend = False)
mlogit_sm = sm.MNLogit(Y, X).fit(maxiter=100)
print (mlogit_sm.summary())   # Perfect separation

Optimization terminated successfully.
         Current function value: nan
         Iterations 26
                          MNLogit Regression Results                          
Dep. Variable:                      y   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      140
Method:                           MLE   Df Model:                            8
Date:                Tue, 27 Aug 2019   Pseudo R-squ.:                     nan
Time:                        08:21:13   Log-Likelihood:                    nan
converged:                       True   LL-Null:                       -164.79
                                        LLR p-value:                       nan
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1                nan        nan        nan        nan         nan         nan
x2                nan        nan 

C:\Users\no1papa\Anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py:2128: RuntimeWarning: invalid value encountered in true_divide
  return eXB/eXB.sum(1)[:,None]
C:\Users\no1papa\Anaconda3\lib\site-packages\statsmodels\base\optimizer.py:271: RuntimeWarning: invalid value encountered in greater
  oldparams) > tol)):
C:\Users\no1papa\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
C:\Users\no1papa\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:877: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
C:\Users\no1papa\Anaconda3\lib\site-packages\scipy\stats\_distn_infrastructure.py:1831: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)


In [60]:
mlogit_sm = sm.MNLogit(Y, X).fit(method='bfgs',maxiter=100)
mlogit_sm.summary()

Optimization terminated successfully.
         Current function value: 0.039662
         Iterations: 65
         Function evaluations: 67
         Gradient evaluations: 67


<class 'statsmodels.iolib.summary.Summary'>
"""
                          MNLogit Regression Results                          
==============================================================================
Dep. Variable:                      y   No. Observations:                  150
Model:                        MNLogit   Df Residuals:                      140
Method:                           MLE   Df Model:                            8
Date:                Tue, 27 Aug 2019   Pseudo R-squ.:                  0.9639
Time:                        08:21:14   Log-Likelihood:                -5.9493
converged:                       True   LL-Null:                       -164.79
                                        LLR p-value:                 7.055e-64
==============================================================================
       y=1       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -5.8833    6.7e+04  -8.79e-05      1.000   -1.31e+05    1.31e+05
x2           -14.4150   4.54e+04     -0.000      1.000    -8.9e+04    8.89e+04
x3            20.6480   8.03e+04      0.000      1.000   -1.57e+05    1.57e+05
x4             2.5831   1.34e+05   1.93e-05      1.000   -2.63e+05    2.63e+05
const         17.6936   2.81e+05   6.29e-05      1.000   -5.51e+05    5.51e+05
------------------------------------------------------------------------------
       y=2       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -8.3486    6.7e+04     -0.000      1.000   -1.31e+05    1.31e+05
x2           -21.0967   4.54e+04     -0.000      1.000    -8.9e+04    8.89e+04
x3            30.0778   8.03e+04      0.000      1.000   -1.57e+05    1.57e+05
x4            20.8670   1.34e+05      0.000      1.000   -2.63e+05    2.63e+05
const        -24.9395   2.81e+05  -8.87e-05      1.000   -5.51e+05    5.51e+05
==============================================================================
"""

In [61]:
prob = mlogit_sm.predict(X)
print(prob)

[[1.00000000e+00 3.31700223e-15 5.12985000e-42]
 [1.00000000e+00 1.45187753e-11 1.03835955e-36]
 [1.00000000e+00 3.34307894e-13 4.00678382e-39]
 [1.00000000e+00 1.58178500e-10 3.11967289e-35]
 [1.00000000e+00 1.41325002e-15 1.43370189e-42]
 [1.00000000e+00 1.46097425e-15 4.88395046e-41]
 [1.00000000e+00 3.43952223e-13 2.21530066e-38]
 [1.00000000e+00 1.99075015e-13 1.97313854e-39]
 [9.99999999e-01 1.16278643e-09 5.56460301e-34]
 [1.00000000e+00 2.09143062e-11 3.16334940e-37]
 [1.00000000e+00 2.50545184e-16 1.24797562e-43]
 [1.00000000e+00 5.09050639e-12 2.12111730e-37]
 [1.00000000e+00 2.01955088e-11 2.96947458e-37]
 [1.00000000e+00 7.80910606e-13 2.32683771e-39]
 [1.00000000e+00 6.43525674e-22 9.51642706e-52]
 [1.00000000e+00 2.98188907e-21 2.55525503e-49]
 [1.00000000e+00 3.78201502e-19 2.90891022e-46]
 [1.00000000e+00 4.29465370e-15 4.13376945e-41]
 [1.00000000e+00 8.16530731e-16 4.08346277e-42]
 [1.00000000e+00 4.48286940e-16 1.49261826e-42]
 [1.00000000e+00 1.17610909e-12 2.866713

In [62]:
yhat = np.argmax(prob,1)
print(yhat)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [63]:
# LASSO with statmodels
from statsmodels.discrete.discrete_model import MNLogit
mlogit_sm = MNLogit(Y,X)
mlogit_smL = mlogit_sm.fit_regularized(method="l1", alpha=0.5)

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 0.18720288836716564
            Iterations: 106
            Function evaluations: 108
            Gradient evaluations: 106


In [64]:
yhatL = np.argmax(mlogit_smL.predict(X),1)
print(yhatL)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [65]:
from sklearn import metrics
print(metrics.confusion_matrix(Y, yhatL))

[[50  0  0]
 [ 0 48  2]
 [ 0  1 49]]


In [66]:
# sklearn
from sklearn.linear_model import LogisticRegression
mlogitR = LogisticRegression(C=1e5)  # multi_class={'ovr','multinomial'}  
X = iris.data[:, :4]
mlogitR.fit(X,Y)
muR = mlogitR.predict_proba(X)
print(muR)

[[9.21716697e-01 7.82833027e-02 2.33566088e-27]
 [7.79476133e-01 2.20523867e-01 8.93341342e-26]
 [8.53254961e-01 1.46745039e-01 1.66609986e-26]
 [7.88652370e-01 2.11347630e-01 2.48705437e-25]
 [9.37128029e-01 6.28719709e-02 1.56501668e-27]
 [9.77119981e-01 2.28800190e-02 5.18264806e-26]
 [9.13153302e-01 8.68466983e-02 9.46660754e-26]
 [8.88526092e-01 1.11473908e-01 1.42641987e-26]
 [7.29395024e-01 2.70604976e-01 5.57294771e-25]
 [7.63419245e-01 2.36580755e-01 1.87160091e-26]
 [9.49465085e-01 5.05349149e-02 7.75964639e-28]
 [8.72133101e-01 1.27866899e-01 5.84566913e-26]
 [7.41836161e-01 2.58163839e-01 1.77301837e-26]
 [7.75680406e-01 2.24319594e-01 3.84185981e-27]
 [9.85572138e-01 1.44278617e-02 2.47528875e-30]
 [9.95802567e-01 4.19743304e-03 1.40422604e-28]
 [9.86211040e-01 1.37889599e-02 1.23867327e-27]
 [9.38361336e-01 6.16386637e-02 1.45923319e-26]
 [9.63907729e-01 3.60922713e-02 7.71829918e-27]
 [9.67595037e-01 3.24049628e-02 5.23810411e-27]
 [8.73615340e-01 1.26384660e-01 3.397602

C:\Users\no1papa\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\no1papa\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [67]:
yhatR = np.argmax(muR,1)
print(yhatR)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [68]:
print(metrics.confusion_matrix(Y, yhatR))

[[50  0  0]
 [ 0 48  2]
 [ 0  1 49]]
